osfCommunityPopUpMessage/objects/OSF_Customer_Message__c/OSF_Customer_Message__c.object-meta.xml
<CustomObject>
    <description>This object is used to store customer messages that can be displayed on the community or storefront.</description>
    <label>OSF Customer Message</label>
    <nameField>
        <label>OSF Customer Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OSF Customer Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

osfCommunityPopUpMessage/objects/OSF_Customer_Message__c/fields/OSF_End_Date__c.field-meta.xml
<CustomField>
    <fullName>OSF_End_Date__c</fullName>
    <defaultValue>TODAY() + 7</defaultValue>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

osfCommunityPopUpMessage/objects/OSF_Customer_Message__c/fields/OSF_Message_Body__c.field-meta.xml
<CustomField>
    <fullName>OSF_Message_Body__c</fullName>
    <label>Message Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

osfCommunityPopUpMessage/objects/OSF_Customer_Message__c/fields/OSF_Message_Sequence__c.field-meta.xml
<CustomField>
    <fullName>OSF_Message_Sequence__c</fullName>
    <label>Message Sequence</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

osfCommunityPopUpMessage/objects/OSF_Customer_Message__c/fields/OSF_Message_Title__c.field-meta.xml
<CustomField>
    <fullName>OSF_Message_Title__c</fullName>
    <description>The title of the message</description>
    <inlineHelpText>Titles of messages are optional</inlineHelpText>
    <label>Message Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

osfCommunityPopUpMessage/objects/OSF_Customer_Message__c/fields/OSF_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>OSF_Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

osfCommunityPopUpMessage/classes/OSF_CommunityPopUpMessageControllerTest.cls
@isTest
public with sharing class OSF_CommunityPopUpMessageControllerTest {

    @TestSetup
    private static void makeData(){
        
        List<OSF_Customer_Message__c> messageList = new List<OSF_Customer_Message__c>();

        // add a valid message
        messageList.add(new OSF_Customer_Message__c(OSF_Message_Title__c =' Test Title 1', OSF_Message_Body__c = 'Test Body 1',
                                                    OSF_Start_Date__c = date.today().addDays(-1), OSF_End_Date__c = date.today().addDays(1),
                                                    OSF_Message_Sequence__c = 1));
        
        // add a second valid message
        messageList.add(new OSF_Customer_Message__c(OSF_Message_Title__c =' Test Title 2', OSF_Message_Body__c = 'Test Body 2',
                                                    OSF_Start_Date__c = date.today().addDays(-2), OSF_End_Date__c = date.today().addDays(2),
                                                    OSF_Message_Sequence__c = 2));
                                   
        // add an old message valid message
        messageList.add(new OSF_Customer_Message__c(OSF_Message_Title__c =' Test Title 3', OSF_Message_Body__c = 'Test Body 3',
                                                    OSF_Start_Date__c = date.today().addDays(-14), OSF_End_Date__c = date.today().addDays(-7),
                                                    OSF_Message_Sequence__c = 3));

        insert messageList;
    }

    @isTest
    private static void testRetrieveValidMessage(){
        List<OSF_Customer_Message__c> messagesList =  OSF_CommunityPopUpMessageController.getCustomerMessages();

        Test.startTest();
        system.assertEquals(2, messagesList.size(), '2 valid messages should have been returned');
        Test.stopTest();
    }
}