osfCommunityPopUpMessage/objects/OSF_Customer_Message__c/OSF_Customer_Message__c.object-meta.xml
<CustomObject>
    <description>This object is used to store customer messages that can be displayed on the community or storefront.</description>
    <label>OSF Customer Message</label>
    <nameField>
        <label>OSF Customer Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OSF Customer Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

osfCommunityPopUpMessage/objects/OSF_Customer_Message__c/fields/OSF_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>OSF_Image_URL__c</fullName>
    <label>Image URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

osfCommunityPopUpMessage/objects/OSF_Customer_Message__c/fields/OSF_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>OSF_Is_Active__c</fullName>
    <formula>AND ( OSF_Start_Date__c &lt;= TODAY(), OSF_End_Date__c &gt;= TODAY())</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

osfCommunityPopUpMessage/objects/OSF_Customer_Message__c/fields/OSF_Message_Body__c.field-meta.xml
<CustomField>
    <fullName>OSF_Message_Body__c</fullName>
    <label>Message Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

osfCommunityPopUpMessage/objects/OSF_Customer_Message__c/fields/OSF_Message_Sequence__c.field-meta.xml
<CustomField>
    <fullName>OSF_Message_Sequence__c</fullName>
    <label>Message Sequence</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

osfCommunityPopUpMessage/objects/OSF_Customer_Message__c/fields/OSF_Message_Title__c.field-meta.xml
<CustomField>
    <fullName>OSF_Message_Title__c</fullName>
    <description>The title of the message</description>
    <inlineHelpText>Titles of messages are optional</inlineHelpText>
    <label>Message Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

osfCommunityPopUpMessage/classes/OSF_CommunityPopUpMessageController.cls
/*------------------------------------------------------------
Author:        Priyanka Kumar
Company:       OSF Digital ANZ
Description:   Apex class to retrieve valid messages for the pop up message component     
Test Class:    OSF_CommunityPopUpMessageControllerTest
<Date>         <Authors Name>     <Brief Description of Change>
07-Oct-2022    Reuben Lim        Picklist preference excludion logic built for BATNZ.
------------------------------------------------------------*/
public with sharing class OSF_CommunityPopUpMessageController {

    // returns a list of customer messages for display on pop-up
    @AuraEnabled(cacheable=true)
    public static List<OSF_Customer_Message__c> getCustomerMessages() {
            return [SELECT OSF_Message_Title__c, OSF_Message_Body__c, OSF_Image_URL__c
                    FROM OSF_Customer_Message__c
                    WHERE OSF_Is_Active__c = TRUE
                    ORDER BY OSF_Message_Sequence__c ASC];
    }
}